# Generated by Django 6.0.4 on 2026-04-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('to-do', 'To-Do'), ('in-progress', 'In-Progress'), ('done', 'Done')], max_length=20)),
                ('priority', models.IntegerField(choices=[(1, 'High '), (2, 'Medium'), (3, 'Low')], default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['priority', '-created_at'],
            },
        ),
    ]
